; Compilation and Linking of YAM.
; 15/Jun/83
pip yamsys.h=yamsor.h
pip hardware.h=hardware.sor
cc yam1.c -e 7100 -x
cc yam2.c -e 7100 -o -x
cc yam3.c -e 7100 -o -x
cc yam5.c -e 7100 -o -x
cc yam7.c -e 7100 -o -x
cc yam10.c -e 7100 -o -x
cc yam11.c -e 7100 -o -x
;l2 yam1 -l yam2 yam3 yam5 yam7 yam89 yam10 yam11 sorkey -o yamsorx
clink yam1 -f yam2 yam3 yam5 yam7 yam89 yam10 yam11 sorkey -r 800 -o yamsorx -s
